extends: ['@commitlint/config-conventional']

rules:
  scope-enum:
    - 2
    - always
    - [
        digger-cleanup,
        digger-comment-guard,
        digger-help,
        digger-job,
        digger-notify-slack,
        digger-workflow,
        semantic-release,
      ]
