extends: ['@commitlint/config-conventional']

rules:
  scope-enum:
    - 2
    - always
    - [
        actionlint,
        dependabot-auto-merge,
        digger,
        pre-commit-autoupdate,
        workflow-keepalive,
      ]
