name: Actionlint

on:
  workflow_call:
  pull_request:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/**/*'

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982 # v1.69.1
        with:
          fail_level: any
          reporter: github-check
