name: Actionlint

on:
  workflow_call:
  pull_request:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/**/*'

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982 # v1.69.1
        with:
          fail_level: any
          reporter: github-check
