name: Digger Job

on:
  workflow_call:
    inputs:
      aws-role-to-assume:
        required: false
        type: string
      config-file:
        required: false
        type: string
        default: digger.yaml
      mode:
        required: false
        type: string
    secrets:
      DIGGER_SLACK_WEBHOOK_URL:
        required: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  digger-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: write       # required for plan persistence
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
    steps:
      - uses: actions/checkout@v4.2.0
        if: github.event_name == 'issue_comment'
        with:
          clean: false
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: actions/checkout@v4.2.0
        if: github.event_name != 'issue_comment'
        with:
          clean: false

      - uses: dawidd6/action-download-artifact@v6
        if: inputs.mode != 'drift-detection'
        with:
          name: builds
          pr: ${{ github.event.pull_request.number || github.event.issue.number }}
          workflow: digger-workflow.yaml
          search_artifacts: true
          if_no_artifact_found: ignore

      - run: |
          mv ${{ inputs.config-file }} "${RUNNER_TEMP}/digger.yaml"
          rm -f digger.yml digger.yaml
          mv "${RUNNER_TEMP}/digger.yaml" .

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(vars || fromJSON('{}')) }}

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets || fromJSON('{}')) }}

      - uses: mikefarah/yq@v4.44.3
        env:
          # this is a slight hack to support yq env substitution for digger provided environment variables
          # https://docs.digger.dev/howto/custom-commands#environment-variables
          DEFAULT_BRANCH: ${DEFAULT_BRANCH}
          DIGGER_OUT: ${DIGGER_OUT}
          PR_BRANCH: ${PR_BRANCH}
          PROJECT_NAME: ${PROJECT_NAME}
        with:
          cmd: >-
            yq -i '
              explode(.) |
              (.collect_usage_data |= false) |
              (.telemetry |= false) |
              (select(has("workflows")) | .workflows[] |= (. as $workflow | .. | select(tag == "!!str") |= ($workflow.env_vars.state[] as $env ireduce (.; sub("\${?" + $env.name + "}?", $env.value))))) // . |
              (del(."x-*")) |
              (.. | select(tag == "!!str")) |= envsubst(nu)
            ' digger.yaml

      - uses: kieranbrown/github-actions/.github/actions/setup-tgenv@v1

      # https://github.com/diggerhq/digger/issues/1179
      - run: sudo echo "127.0.0.1 analytics.digger.dev" | sudo tee -a /etc/hosts

      - uses: diggerhq/digger@v0.6.44
        env:
          AWS_REGION: us-east-1
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY: false
          TERRAGRUNT_NON_INTERACTIVE: true
          TF_IN_AUTOMATION: true
          TF_VAR_ci: true
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-to-assume: ${{ inputs.aws-role-to-assume }}
          cache-dependencies: true
          configure-checkout: false
          disable-locking: true
          drift-detection-slack-notification-url: ${{ secrets.DIGGER_SLACK_WEBHOOK_URL }}
          mode: ${{ inputs.mode }}
          no-backend: true
          setup-aws: ${{ inputs.aws-role-to-assume && true }}
          setup-tfenv: true
          upload-plan-destination: ${{ inputs.mode != 'drift-detection' && 'github' }}

      - uses: actions/upload-artifact@v4.4.0
        if: inputs.mode != 'drift-detection'
        with:
          name: builds
          path: '**/builds'
          if-no-files-found: ignore
          retention-days: 90 # cleaned up once PR is closed
