name: Digger Job

on:
  workflow_call:
    inputs:
      aws-role-to-assume:
        required: false
        type: string
      config-file:
        required: false
        type: string
        default: digger.yaml
      mode:
        required: false
        type: string
      upload-plan-destination:
        required: false
        type: string
        default: ${{ github.event.repository.private && 'github' }}
    secrets:
      DIGGER_SLACK_WEBHOOK_URL:
        required: false

jobs:
  digger-job:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      actions: write       # required for plan persistence
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      issues: write        # required to create drift issues
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
    steps:
      - uses: kieranbrown/github-actions/.github/actions/setup-tgenv@v1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: github.event_name == 'issue_comment'
        with:
          clean: false
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: github.event_name != 'issue_comment'
        with:
          clean: false

      - run: |
          mv ${{ inputs.config-file }} "${RUNNER_TEMP}/digger.yaml"
          rm -f digger.yml digger.yaml
          mv "${RUNNER_TEMP}/digger.yaml" .

      - uses: dawidd6/action-download-artifact@d63b86af1b34672e53c440b1b83979861906bad7 # v24
        if: inputs.mode != 'drift-detection'
        with:
          name: builds
          pr: ${{ github.event.pull_request.number || github.event.issue.number }}
          workflow: digger-workflow.yaml
          search_artifacts: true
          if_no_artifact_found: ignore

      - uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        if: inputs.aws-role-to-assume
        with:
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-to-assume: ${{ inputs.aws-role-to-assume }}

      - uses: oNaiPs/secrets-to-env-action@75f319b3c8c926ac2eabcca34daa6cf531daf32f # v1.8
        with:
          secrets: ${{ toJSON(vars || fromJSON('{}')) }}

      - uses: oNaiPs/secrets-to-env-action@75f319b3c8c926ac2eabcca34daa6cf531daf32f # v1.8
        with:
          secrets: ${{ toJSON(secrets || fromJSON('{}')) }}

      - name: Process digger.yaml with yq
        env:
          # this is a slight hack to support yq env substitution for digger provided environment variables
          # https://docs.digger.dev/howto/custom-commands#environment-variables
          DEFAULT_BRANCH: ${DEFAULT_BRANCH}
          DIGGER_OUT: ${DIGGER_OUT}
          PR_BRANCH: ${PR_BRANCH}
          PROJECT_NAME: ${PROJECT_NAME}
        run: |-
          # shellcheck disable=SC2016
          yq -i '
            explode(.) |
            (.collect_usage_data |= false) |
            (.telemetry |= false) |
            (select(has("workflows")) | .workflows[] |= (. as $workflow | .. | select(tag == "!!str") |= ($workflow.env_vars.state[] as $env ireduce (.; sub("\${?" + $env.name + "}?", $env.value))))) // . |
            (del(."x-*")) |
            (.. | select(tag == "!!str")) |= envsubst(nu)
          ' digger.yaml

      - uses: diggerhq/digger@3053cda26247aa3cb94dcd4b8a253ee3cbc78243 # v0.6.149
        env:
          AWS_REGION: us-east-1 # required since https://github.com/diggerhq/digger/pull/1350
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY: false
          TERRAGRUNT_NON_INTERACTIVE: true
          TF_IN_AUTOMATION: true
          TF_VAR_ci: true
        with:
          # cache-dependencies: true # disabled as digger is generating huge cache artifacts which is slow to restore
          configure-checkout: false
          disable-locking: true
          drift-detection-slack-notification-url: ${{ secrets.DIGGER_SLACK_WEBHOOK_URL }}
          mode: ${{ inputs.mode }}
          no-backend: true
          setup-tfenv: true
          upload-plan-destination: ${{ inputs.mode != 'drift-detection' && inputs.upload-plan-destination }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: inputs.mode != 'drift-detection'
        with:
          name: builds
          path: |
            **/builds
            **/*.zip
          if-no-files-found: ignore
          retention-days: 90 # cleaned up once PR is closed
