name: Digger Notify Slack

on:
  workflow_call:
    secrets:
      DIGGER_SLACK_WEBHOOK_URL:
        required: false

jobs:
  digger-notify-slack:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        if: env.SLACK_WEBHOOK_URL
        with:
          webhook: ${{ secrets.DIGGER_SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            text: "Digger workflow completed in repository <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }}>"
