name: Digger Notify Slack

on:
  workflow_call:
    secrets:
      DIGGER_SLACK_WEBHOOK_URL:
        required: false

jobs:
  digger-notify-slack:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions: {}
    steps:
      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: env.SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DIGGER_SLACK_WEBHOOK_URL }}
        with:
          webhook: ${{ secrets.DIGGER_SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            text: "Digger workflow completed in repository <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }}>"
