name: Pre-commit AutoUpdate

on:
  workflow_call:
  schedule: ## 5am every week on Saturday
    - cron: '0 5 * * 6'

jobs:
  autoupdate:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12
          # cache: pip

      - run: pip install pre-commit==3.7.1

      - run: |
          UPDATE_MESSAGE=$(pre-commit autoupdate | grep -i 'updating' | grep -v 'Updating dependencies' | sed 's/Updating//g')
          echo "$UPDATE_MESSAGE"
          {
            echo "UPDATE_MESSAGE<<EOF"
            echo "${UPDATE_MESSAGE}"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          title: 'chore(deps): update pre-commit hooks'
          branch: pre-commit-update-hooks
          commit-message: 'chore(deps): update pre-commit hooks'
          delete-branch: true
          body: |
            Bumps the following `pre-commit` hooks.

            ```text
            ${{ env.UPDATE_MESSAGE }}
            ```

  workflow-keepalive:
    uses: ./.github/workflows/workflow-keepalive.yaml
    permissions:
      actions: write
